# -*- coding: utf-8 -*-
"""Fraud_detection_projec

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nV3gpSr94pHi4_oJWt0AhvUslVEeEMcy
"""

!pip install kaggle imbalanced-learn xgboost shap streamlit -q

!mkdir -p ~/.kaggle
!echo 'KGAT_be19b27d37094405c56376fff65eb16c' > ~/.kaggle/access_token
!chmod 600 ~/.kaggle/access_token

!kaggle datasets list

!kaggle datasets download -d mlg-ulb/creditcardfraud
!unzip -q creditcardfraud.zip

!unzip -q creditcardfraud.zip

!unzip -o -q creditcardfraud.zip

import pandas as pd

df = pd.read_csv('creditcard.csv')
print(df.shape)
print(df['Class'].value_counts())
print(df['Class'].value_counts(normalize=True) * 100)
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')

plt.figure(figsize=(6,4))
sns.countplot(x='Class', data=df)
plt.title('Class Distribution (0 = Normal, 1 = Fraud)')
plt.yscale('log')  # log scale because fraud count is so tiny it'd be invisible otherwise
plt.show()

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
sns.histplot(df[df['Class']==0]['Amount'], bins=50, color='blue')
plt.title('Amount - Normal Transactions')
plt.xlim(0,2000)

plt.subplot(1,2,2)
sns.histplot(df[df['Class']==1]['Amount'], bins=50, color='red')
plt.title('Amount - Fraud Transactions')
plt.xlim(0,2000)

plt.tight_layout()
plt.show()

print("Normal transactions - Amount stats:")
print(df[df['Class']==0]['Amount'].describe())
print("\nFraud transactions - Amount stats:")
print(df[df['Class']==1]['Amount'].describe())

from sklearn.model_selection import train_test_split

X = df.drop('Class', axis=1)
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)
print("Fraud in train:", y_train.sum())
print("Fraud in test:", y_test.sum())

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("Before SMOTE:", y_train.value_counts())
print("\nAfter SMOTE:", y_train_smote.value_counts())

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train_smote, y_train_smote)

y_pred_lr = lr.predict(X_test)

print("Logistic Regression Results:")
print(classification_report(y_test, y_pred_lr))
print("ROC-AUC:", roc_auc_score(y_test, lr.predict_proba(X_test)[:,1]))

from xgboost import XGBClassifier

xgb = XGBClassifier(random_state=42, eval_metric='logloss')
xgb.fit(X_train_smote, y_train_smote)

y_pred_xgb = xgb.predict(X_test)

print("XGBoost Results:")
print(classification_report(y_test, y_pred_xgb))
print("ROC-AUC:", roc_auc_score(y_test, xgb.predict_proba(X_test)[:,1]))

import shap

explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test)

# Pick one fraud case from test set and explain that specific prediction
fraud_idx = y_test[y_test==1].index[0]
idx_pos = X_test.index.get_loc(fraud_idx)

shap.force_plot(explainer.expected_value, shap_values[idx_pos], X_test.iloc[idx_pos], matplotlib=True)

!pip install pyngrok -q

import joblib

joblib.dump(xgb, 'fraud_model.pkl')
print("Model saved!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import joblib
# import shap
# import matplotlib.pyplot as plt
# 
# st.title("💳 Fraud Detection Demo")
# st.write("Upload transaction data or enter values manually to check fraud probability.")
# 
# model = joblib.load('fraud_model.pkl')
# 
# uploaded_file = st.file_uploader("Upload a CSV of transactions", type="csv")
# 
# if uploaded_file is not None:
#     data = pd.read_csv(uploaded_file)
#     st.write("Preview of uploaded data:", data.head())
# 
#     if st.button("Predict Fraud"):
#         preds = model.predict(data)
#         probs = model.predict_proba(data)[:, 1]
#         data['Fraud_Prediction'] = preds
#         data['Fraud_Probability'] = probs
#         st.write(data[['Fraud_Prediction', 'Fraud_Probability']])
# 
#         # SHAP explanation for first row
#         explainer = shap.TreeExplainer(model)
#         shap_values = explainer.shap_values(data.drop(columns=['Fraud_Prediction','Fraud_Probability'], errors='ignore'))
#         st.write("SHAP explanation for first transaction:")
#         fig, ax = plt.subplots()
#         shap.force_plot(explainer.expected_value, shap_values[0],
#                          data.drop(columns=['Fraud_Prediction','Fraud_Probability'], errors='ignore').iloc[0],
#                          matplotlib=True, show=False)
#         st.pyplot(fig)

from pyngrok import ngrok

ngrok.set_auth_token("3J4qbOEnPEYd9jIHSxizrz0xLQo_2oY45QUG26r8iJwbByUon")

import subprocess
import time

subprocess.Popen(['streamlit', 'run', 'app.py', '--server.port', '8501'])
time.sleep(5)

public_url = ngrok.connect(8501)
print("Your app is live at:", public_url)

# Create a small sample CSV to test the app (a few rows, no Class column)
sample = X_test.iloc[:10]  # first 10 test transactions
sample.to_csv('sample_transactions.csv', index=False)
print("Sample file created — download it from the Colab file browser (folder icon on left sidebar)")

